### ISSUE TITLE
malloc的问题

### ISSUE THREAD

**Issue by yyyiue** [winshining/webbench-plus-post#1]
header->header = (char **)malloc(header->count)
size不应该是header->count * sizeof(char*)吗？

**Comment by winshining** [comment]
我看了，是有问题，不过你说的也有问题，应该是：
header->header = (char **)malloc(header->count * sizeof(char *));
代码已经更新了:)

**Comment by yyyiue** [comment]
对，打错了。。。谢谢你的源码，学到了很多，哈哈。
